# OSTATECZNA WERSJA docker-compose.yml
services:
  matplast-slideshow-app:
    container_name: matplast-slideshow
    restart: unless-stopped
    build: .
    ports:
      - "8080:5000"
    volumes:
      - "/DATA/AppData/matplast-slideshow/images:/app/static/images"
    
    # Metadane wymagane przez App Store w CasaOS
    x-casaos:
      architectures:
        - amd64
        - arm64
      main: matplast-slideshow-app
      description:
        en_us: A synchronized photo slideshow kiosk for company screens.
        pl_pl: Zsynchronizowany kiosk do pokazu zdjęć na firmowych ekranach.
      tagline:
        en_us: Photo Slideshow Kiosk
        pl_pl: Kiosk z pokazem zdjęć
      developer: "noseczek12"
      author: "noseczek12"
      icon: "https://cdn.icon-icons.com/icons2/2090/PNG/512/slideshow_icon_128362.png"
      thumbnail: ""
      title:
        en_us: Matplast Slideshow
        pl_pl: Pokaz slajdów Matplast
      category: "Custom"
      port_map: "8080"